//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giftlist
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GiftlistEntities : DbContext
    {
        public GiftlistEntities()
            : base("name=GiftlistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClaimType> ClaimTypes { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<ItemClaim> ItemClaims { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
