//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giftlist
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemClaim
    {
        public int ItemClaimId { get; set; }
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public int ClaimTypeId { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual User User { get; set; }
        public virtual ClaimType ClaimType { get; set; }
    }
}
