//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giftlist
{
    using System;
    using System.Collections.Generic;

    [Serializable]
    public partial class Item
    {
        public Item()
        {
            this.ItemClaims = new HashSet<ItemClaim>();
        }
    
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int PriorityId { get; set; }
        public string Url { get; set; }
        public string ImagePath { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ItemClaim> ItemClaims { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual User User { get; set; }
    }
}
