//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giftlist
{
    using System;
    using System.Collections.Generic;
    
	[Serializable]
    public partial class Priority
    {
        public Priority()
        {
            this.Items = new HashSet<Item>();
        }
    
        public int PriorityId { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
    }
}
