//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Giftlist
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ItemClaims = new HashSet<ItemClaim>();
            this.Items = new HashSet<Item>();
            this.Families = new HashSet<Family>();
        }
    
        public int UserId { get; set; }
        public int UserTypeId { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<ItemClaim> ItemClaims { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<Family> Families { get; set; }
    }
}
